version: '3'

services:
  db:
    image: mysql
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=password
           - MYSQL_DATABASE=db
           - MYSQL_USER=ticket-admin
           - MYSQL_PASSWORD=admin
    volumes:
           - my-db:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./
    ports:
           - "8080:8080"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ../UrbanTicketSystemFrontend/urban-ticket-system/
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:4200"
volumes:
    my-db: