version: 2.1

workflows:
  build-deploy:
    jobs:
      - build-deploy
jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: mvn clean package
      - run:
          name: Build and push docker image to heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a urban-ticket-system-backend web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a urban-ticket-system-backend web